# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/qt/SmartDataWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmartDataWidget(object):
    def setupUi(self, SmartDataWidget):
        SmartDataWidget.setObjectName("SmartDataWidget")
        SmartDataWidget.resize(702, 499)
        self.verticalLayout = QtWidgets.QVBoxLayout(SmartDataWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(SmartDataWidget)
        self.searchLineEdit.setText("")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.verticalLayout.addWidget(self.searchLineEdit)
        self.treeWidget = QtWidgets.QTreeWidget(SmartDataWidget)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWidget.setIconSize(QtCore.QSize(5, 5))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Key")
        self.verticalLayout.addWidget(self.treeWidget)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SmartDataWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.statusLineEdit = QtWidgets.QLineEdit(SmartDataWidget)
        self.statusLineEdit.setEnabled(False)
        self.statusLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLineEdit.setObjectName("statusLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.statusLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exportButton = QtWidgets.QPushButton(SmartDataWidget)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.closeButton = QtWidgets.QPushButton(SmartDataWidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionCollapse_All = QtWidgets.QAction(SmartDataWidget)
        self.actionCollapse_All.setObjectName("actionCollapse_All")
        self.actionExpand_All = QtWidgets.QAction(SmartDataWidget)
        self.actionExpand_All.setObjectName("actionExpand_All")

        self.retranslateUi(SmartDataWidget)
        QtCore.QMetaObject.connectSlotsByName(SmartDataWidget)

    def retranslateUi(self, SmartDataWidget):
        _translate = QtCore.QCoreApplication.translate
        SmartDataWidget.setWindowTitle(_translate("SmartDataWidget", "SMART Data - ?"))
        self.searchLineEdit.setPlaceholderText(_translate("SmartDataWidget", "Search key ..."))
        self.treeWidget.headerItem().setText(1, _translate("SmartDataWidget", "Value"))
        self.label.setText(_translate("SmartDataWidget", "Drive status"))
        self.exportButton.setText(_translate("SmartDataWidget", "Export Data"))
        self.closeButton.setText(_translate("SmartDataWidget", "Close"))
        self.actionCollapse_All.setText(_translate("SmartDataWidget", "Collapse All"))
        self.actionExpand_All.setText(_translate("SmartDataWidget", "Expand All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SmartDataWidget = QtWidgets.QWidget()
    ui = Ui_SmartDataWidget()
    ui.setupUi(SmartDataWidget)
    SmartDataWidget.show()
    sys.exit(app.exec_())
